<?php

/**
 * @file
 * Contains dc_discussion.module.
 */

use Drupal\Core\Database\Database;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;

/**
 * Implements hook_help().
 */
function dc_discussion_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dc_discussion module.
    case 'help.page.dc_discussion':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DrupalCenter discussion related tweaks.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dc_discussion_form_node_discussion_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Get current route..
  $route = \Drupal::service('current_route_match');

  // Start new discussion.
  if ($route->getRouteName() == 'node.add') {
    // Hide field field_parent on default node.add pages.
    if (!empty($form['field_parent'])) {
      $form['field_parent']['#access'] = FALSE;
    }
  }

  // Add new discussion answer.
  if ($route->getRouteName() == 'node.add_discussion_answer') {
    $node = Node::load($route->getParameter('node'));
    // Prepopulate field_parent with node id from url.
    if ($node instanceof NodeInterface) {
      $form['field_parent']['widget'][0]['target_id']['#default_value'] = $node;
      // Hide field_parent for discussion answers.
      $form['field_parent']['#access'] = FALSE;
      // Hide field_drupal_version for discussion answers.
      $form['field_drupal_version']['#access'] = FALSE;
      // Hide field_discussion_category for discussion answers.
      $form['field_discussion_category']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dc_discussion_form_node_discussion_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $node = $form_state->getFormObject()->getEntity();

  // Hide field_parent for disussion edit form.
  $form['field_parent']['#access'] = FALSE;

  // Check for filled field_parent and hide fields
  if ($node instanceof NodeInterface && ($node->hasField('field_parent') && !empty($node->get('field_parent')->getValue()[0]))) {
    // Hide field_drupal_version while editing discussion answers.
    $form['field_drupal_version']['#access'] = FALSE;
    $form['field_discussion_category']['#access'] = FALSE;
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function dc_discussion_entity_extra_field_info() {
  $extra = [];
  // Add extra fields to node type discussion.
  // Add field discussion answers.
  $extra['node']['discussion']['display']['discussion_answers'] = [
    'label' => t('Discussion answers'),
    'weight' => 100,
  ];
  // Add field answer count.
  $extra['node']['discussion']['display']['answer_count'] = [
    'label' => t('Answer count'),
    'weight' => 100,
  ];
  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function dc_discussion_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  switch ($entity->bundle()) {
    case 'discussion':
      if (($answers = $display->getComponent('discussion_answers')) !== NULL) {
        // Show view discussion answers with actual node id as parent argument.
        $build['discussion_answers'] = views_embed_view('discussion_answers', 'answers', $entity->id());
        $build['discussion_answers']['#weight'] = $answers['weight'];
      }
      if (($count = $display->getComponent('answer_count')) !== NULL) {
        $answers = _dc_discussion_discussion_get_answers($entity->id());
        $build['answer_count'] = [
          '#markup' => count($answers),
          '#weight' => $count['weight'],
        ];
      }
      break;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dc_discussion_form_taxonomy_term_discussion_category_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['field_color']['widget'][0]['value']['#field_prefix'] = '#';
}

/**
 * Helper function to get all answers (as flat list) for a single discussion.
 *
 * @todo: implement as cachable service?
 *
 * @param int $id
 *   Entity ID.
 *
 * @return int[]
 *   List of discussion answer IDs.
 */
function _dc_discussion_discussion_get_answers($id) {
  $query = Database::getConnection()->select('node__field_parent', 'p');
  $query->condition('field_parent_target_id', $id);
  $query->fields('p', ['entity_id', 'revision_id']);

  $ids = $query->execute()->fetchAllKeyed();

  foreach (array_keys($ids) as $id) {
    $ids = array_merge($ids, _dc_discussion_discussion_get_answers($id));
  }

  return $ids;
}
