<?php

/**
 * @file
 * Contains relevant functions for dc_relation.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\dc_relation\Entity\DiscussionRelation;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function dc_relation_node_insert(EntityInterface $entity) {
  DiscussionRelation::updateOrCreateFromEntity($entity);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function dc_relation_node_update(EntityInterface $entity) {
  DiscussionRelation::updateOrCreateFromEntity($entity);
}
