<?php

/**
 * @file
 * Contains dc_ui.module.
 */

use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_form_FORM_ID_alter().
 */
function dc_ui_form_taxonomy_term_drupal_version_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Hide fieldset relations - we only have a flat hierarchy.
  $form['relations']['#required'] = FALSE;
  $form['relations']['#access'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dc_ui_form_taxonomy_term_showroom_category_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Hide fieldset relations - we only have a flat hierarchy.
  $form['relations']['#required'] = FALSE;
  $form['relations']['#access'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dc_ui_form_taxonomy_term_news_category_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Hide fieldset relations - we only have a flat hierarchy.
  $form['relations']['#required'] = FALSE;
  $form['relations']['#access'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dc_ui_form_node_book_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add access check for body field.
  $form['field_legacy_content']['#access'] = _dc_ui_access_legacy_content_field();
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dc_ui_form_node_book_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add access check for body field.
  $form['field_legacy_content']['#access'] = _dc_ui_access_legacy_content_field();
}

/**
 * Helper function to check for user role.
 *
 */
function _dc_ui_access_legacy_content_field() {
  $user_roles = \Drupal::currentUser()->getRoles();
  if(in_array("administrator", $user_roles)) {
    return TRUE;
  }
  return FALSE;
}